<a href="https://colab.research.google.com/github/pab10dm/pab10dm/blob/main/clase03EquilibrioInestEstable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!apt install octave

In [ ]:
!apt install octave-symbolic


In [ ]:
%%writefile Controlador.m
clear all; clc;
setenv PYTHON /usr/bin/python %Acá está el vinculo con Pyton, para acceder al sympy desde symbolic
%/usr/bin/python
pkg load symbolic %Primera vez que se corre el paquete simbólico de Python. 
syms fi fi_p fi_pp p p_p p_pp M m u long Fricc g; 
disp('Para el equilibrio inestable') 
ang_inic=0; 
p_pp=(1/(M+m))*(u-m*long*fi_pp+m*long*fi_p^2*fi-Fricc*p_p); %Pequeños angulos 
% fi_pp_=(1/long)*(g*sin(fi)-p_pp*cos(fi));%Expresión completa 
% fi_pp=(1/long)*(g*(fi)-p_pp); %Pequeños angulos para fi~0, sin(fi)~fi, cos(fi)~1 
fi_pp=solve(fi_pp==(1/long)*(g*fi-p_pp),fi_pp); 
%disp('fi_pp='); pretty(simplify(fi_pp)); 
p_pp=subs(p_pp,'fi_pp',fi_pp); 
%disp('p_pp='); pretty(simplify(p_pp)) 
Mat_A=[[0 1 0 0]; 
[subs(subs(subs(subs(diff(p_pp, p), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
subs(subs(subs(subs(diff(p_pp, p_p), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
subs(subs(subs(subs(diff(p_pp, fi), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
subs(subs(subs(subs(diff(p_pp, fi_p), p,0),p_p,0),fi,ang_inic),fi_p,0)]; 
[0 0 0 1]; 
[subs(subs(subs(subs(diff(fi_pp, p), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
subs(subs(subs(subs(diff(fi_pp, p_p), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
subs(subs(subs(subs(diff(fi_pp, fi), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
subs(subs(subs(subs(diff(fi_pp, fi_p), p,0),p_p,0),fi,ang_inic),fi_p,0)]]; 
Mat_B=[0; 
subs(subs(subs(subs(diff(p_pp, u), p,0),p_p,0),fi,ang_inic),fi_p,0);... 
0; 
subs(subs(subs(subs(diff(fi_pp, u), p,0),p_p,0),fi,ang_inic),fi_p,0)]; 
disp('A=')
pretty(simplify(Mat_A)) 
disp('B=')
pretty(simplify(Mat_B))
syms Mat_C;
Mat_C=[[1 0 0 0];[0 0 1 0]];
disp('C=')
(Mat_C)
disp('D=0')
syms fi fi_p fi_pp p p_p p_pp M m u long Fricc g; 
disp('Para el equilibrio estable') 
ang_inic=pi; 
p_pp=(1/(M+m))*(u+m*long*fi_pp-m*long*fi_p^2*fi-Fricc*p_p); 
%fi_pp=(1/long)*(-g*(fi)+p_pp); %Pequeños angulos para fi~pi sin(fi)~-fi, cos(fi)=-1 
fi_pp=solve(fi_pp==(1/long)*(-g*fi+p_pp),fi_pp); 
disp('fi_pp='); pretty(simplify(fi_pp)); 
p_pp=subs(p_pp,'fi_pp',fi_pp); 
 Mat_A=[[0 1 0 0]; 
    [subs(subs(subs(subs(diff(p_pp, p), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
     subs(subs(subs(subs(diff(p_pp, p_p), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
     subs(subs(subs(subs(diff(p_pp, fi), p,0),p_p,0),fi,ang_inic),fi_p,0), ... 
     subs(subs(subs(subs(diff(p_pp, fi_p), p,0),p_p,0),fi,ang_inic),fi_p,0)]; ... 
     [0 0 0 1];... 
    [subs(subs(subs(subs(diff(fi_pp, p), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
     subs(subs(subs(subs(diff(fi_pp, p_p), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
     subs(subs(subs(subs(diff(fi_pp, fi), p,0),p_p,0),fi,ang_inic),fi_p,0),... 
     subs(subs(subs(subs(diff(fi_pp, fi_p), p,0),p_p,0),fi,ang_inic),fi_p,0)]]; 
  Mat_B=[0; 
     subs(subs(subs(subs(diff(p_pp, u), p,0),p_p,0),fi,ang_inic),fi_p,0);... 
     0; 
     subs(subs(subs(subs(diff(fi_pp, u), p,0),p_p,0),fi,ang_inic),fi_p,0)]; 
  pretty(simplify(Mat_A)) 
  pretty(simplify(Mat_B))

Writing Controlador.m


In [ ]:
!octave -W Controlador.m


OctSymPy v2.6.0: this is free software without warranty, see source.
Initializing communication with SymPy using a popen2() pipe.
Some output from the Python subprocess (pid 3719) might appear next.
Python 2.7.17 (default, Jul  1 2022, 15:56:32) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> >>> 
OctSymPy: Communication established.  SymPy v1.1.1.
Para el equilibrio inestable
A=
  ⎡0     1         0      0⎤
  ⎢                        ⎥
  ⎢   -Fricc     -g⋅m      ⎥
  ⎢0  ───────    ─────    0⎥
  ⎢      M         M       ⎥
  ⎢                        ⎥
  ⎢0     0         0      1⎥
  ⎢                        ⎥
  ⎢   Fricc    g⋅(M + m)   ⎥
  ⎢0  ──────   ─────────  0⎥
  ⎣   M⋅long     M⋅long    ⎦
B=
  ⎡  0   ⎤
  ⎢      ⎥
  ⎢  1   ⎥
  ⎢  ─   ⎥
  ⎢  M   ⎥
  ⎢      ⎥
  ⎢  0   ⎥
  ⎢      ⎥
  ⎢ -1   ⎥
  ⎢──────⎥
  ⎣M⋅long⎦
C=
Mat_C =

   1   0   0   0
   0   0   1   0

D=0
Para el equilibrio estable
fi_pp=
                               2       